aws_region           = "ca-central-1"
environment          = "prod"
domain_name          = "permit-pulse.ca"
github_repo_reviewer = "dyf102/city-permit-reviewer"
github_repo_check    = "dyf102/toronto-permit-pulse"
cloudflare_zone_id   = "0219c4ec09c49f40bcd19e518cd9e0ac"
